project:
  type: website
  output-dir: docs
  resources:
    - src/js/

website:
  title: "Jeffrey's Git Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: morph
      dark: cyborg
    include-after-body: components/scripts.html
    css: styles.css
    toc: true



